apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: my-unsplash
build:
  artifacts:
  - image: bineetnaidu/myunsplash-auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - k8s/auth-depl.yaml
    - k8s/ingress-srv.yaml
